import requests
from crewai.tools import tool
from config import settings

@tool
def fetch_deep_learning_forecast(project_id: int, burn_rate: float, team_size: int) -> str:
    """
    Connects to the enterprise deep learning prediction engine. 
    Passes contextual project variables to the neural network to retrieve calculated predictions for total cost and risk level.
    Use this when you need absolute predictive metrics on a project.
    """
    try:
        # AI Engine runs on port 8001
        base_url = settings.AI_ENGINE_BASE_URL or "http://127.0.0.1:8001"
        
        # 1. Ask for Cost Prediction (XGBoost)
        cost_resp = requests.post(f"{base_url}/predict/cost", json={
            "project_id": project_id,
            "burn_rate": burn_rate,
            "team_size": team_size
        })
        
        # 2. Ask for Risk Prediction (Random Forest)
        risk_resp = requests.post(f"{base_url}/predict/risk", json={
            "project_id": project_id
        })
        
        return f"Predictive Engine Output -> Cost Forecast: {cost_resp.json()}, Risk Assessment: {risk_resp.json()}"
        
    except Exception as e:
        return f"AI Prediction Engine Error: {str(e)}"

@tool
def fetch_revenue_prediction(project_id: int, budget_pct: float) -> str:
    """
    Calls the LightGBM RevenueForecaster model. 
    Predicts the expected revenue/ROI generated by this project.
    """
    try:
        base_url = settings.AI_ENGINE_BASE_URL or "http://127.0.0.1:8001"
        resp = requests.post(f"{base_url}/predict/revenue", json={
            "project_id": project_id,
            "budget_pct": budget_pct
        })
        return f"Revenue Forecast Output (LightGBM): {resp.json()}"
    except Exception as e:
        return f"Revenue Prediction Error: {str(e)}"

@tool
def fetch_cashflow_forecast() -> str:
    """
    Calls the Bidirectional LSTM model for a 90-day cash flow forecast.
    Useful for executive summaries on company-wide financial health.
    """
    try:
        base_url = settings.AI_ENGINE_BASE_URL or "http://127.0.0.1:8001"
        resp = requests.post(f"{base_url}/predict/cashflow", json={})
        return f"90-Day Cash Flow Forecast (LSTM): {resp.json()}"
    except Exception as e:
        return f"Cash Flow Forecast Error: {str(e)}"

@tool
def scan_project_anomalies(amount: float, category: str) -> str:
    """
    Calls the Isolation Forest Anomaly Detection Engine.
    Use this to verify if an expense amount looks suspicious or anomalous.
    """
    try:
        base_url = settings.AI_ENGINE_BASE_URL or "http://127.0.0.1:8001"
        resp = requests.post(f"{base_url}/anomaly/scan", json={
            "amount": amount,
            "category": category
        })
        return f"Anomaly Detection Result (Isolation Forest): {resp.json()}"
    except Exception as e:
        return f"Anomaly Scan Error: {str(e)}"
